version: '3.9'

services:
  
  database:
    image: mongo:6
    container_name: database
    restart: always
    ports:
      - 27017:27017
    volumes:
      - ./data/db:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=nttucsiesec512!

  backend:
    image: hibana2077/NTTUOJ-backend:latest
    container_name: backend
    restart: always
    links:
      - "database"
    ports:
      - 8000:8000
    volumes:
      - ./data/backend:/data
    environment:
      - MONGO_URL=mongodb://database:27017
      - MONGO_USER=root
      - MONGO_PASSWORD=nttucsiesec512!
      - BACKEND_ADMIN_USERNAME=admin
      - BACKEND_ADMIN_PASSWORD=nttucsiesec512!

  frontend:
    image: hibana2077/NTTUOJ-frontend:latest
    container_name: frontend
    restart: always
    ports:
      - 80:80
    links:
      - "backend"
    volumes:
      - ./data/frontend:/data